version: "3.9"

services:
  redis:
    image: redis:7
    container_name: after_sales_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: after_sales_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: aftersales
      RABBITMQ_DEFAULT_PASS: aftersales123

  postgres:
    image: pgvector/pgvector:pg16
    container_name: after_sales_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: after_sales_vector
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
